all:
  hosts:
    r1.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 27.38.6.38
    r10.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 97.197.100.94
    r11.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 51.78.107.24
    r12.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 115.117.137.213
    r13.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 166.191.140.20
    r14.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 93.151.78.231
    r15.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 115.130.72.200
    r16.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 166.132.182.111
    r17.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 4.146.119.4
    r18.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 200.71.158.62
    r19.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 67.57.211.196
    r2.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 5.14.109.20
    r20.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 119.123.151.144
    r21.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 196.0.125.45
    r22.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 44.159.4.90
    r23.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 102.190.241.92
    r24.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 33.29.40.181
    r25.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 191.200.23.89
    r26.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 110.107.98.213
    r27.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 3.161.124.125
    r28.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 134.100.91.108
    r29.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 188.204.44.223
    r3.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 10.169.131.218
    r30.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 204.209.50.179
    r4.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 192.151.132.155
    r5.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 32.124.77.196
    r6.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 111.83.81.25
    r7.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 134.152.154.201
    r8.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 161.206.135.77
    r9.cisco.com:
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_password: C1sc0!23
      ansible_user: cisco
      asn: 65538
      loopback0: 146.175.27.66
