---
- hosts: all
  gather_facts: no
  tasks:
    - name: cisco cfg backup
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: output/ansible/