r1.cisco.com:
  data:
    asn: 65538
    loopback0: 32.236.101.254
  hostname: r1.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r10.cisco.com:
  data:
    asn: 65538
    loopback0: 207.248.225.70
  hostname: r10.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r100.cisco.com:
  data:
    asn: 65538
    loopback0: 92.160.44.21
  hostname: r100.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r11.cisco.com:
  data:
    asn: 65538
    loopback0: 17.236.221.66
  hostname: r11.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r12.cisco.com:
  data:
    asn: 65538
    loopback0: 205.11.37.251
  hostname: r12.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r13.cisco.com:
  data:
    asn: 65538
    loopback0: 73.254.224.85
  hostname: r13.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r14.cisco.com:
  data:
    asn: 65538
    loopback0: 185.185.205.218
  hostname: r14.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r15.cisco.com:
  data:
    asn: 65538
    loopback0: 25.100.208.69
  hostname: r15.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r16.cisco.com:
  data:
    asn: 65538
    loopback0: 193.117.75.206
  hostname: r16.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r17.cisco.com:
  data:
    asn: 65538
    loopback0: 165.145.137.233
  hostname: r17.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r18.cisco.com:
  data:
    asn: 65538
    loopback0: 120.253.127.22
  hostname: r18.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r19.cisco.com:
  data:
    asn: 65538
    loopback0: 163.222.70.228
  hostname: r19.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r2.cisco.com:
  data:
    asn: 65538
    loopback0: 68.250.139.154
  hostname: r2.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r20.cisco.com:
  data:
    asn: 65538
    loopback0: 197.60.72.142
  hostname: r20.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r21.cisco.com:
  data:
    asn: 65538
    loopback0: 108.9.92.141
  hostname: r21.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r22.cisco.com:
  data:
    asn: 65538
    loopback0: 149.24.118.84
  hostname: r22.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r23.cisco.com:
  data:
    asn: 65538
    loopback0: 211.227.123.180
  hostname: r23.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r24.cisco.com:
  data:
    asn: 65538
    loopback0: 207.87.53.209
  hostname: r24.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r25.cisco.com:
  data:
    asn: 65538
    loopback0: 195.212.250.127
  hostname: r25.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r26.cisco.com:
  data:
    asn: 65538
    loopback0: 170.254.71.232
  hostname: r26.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r27.cisco.com:
  data:
    asn: 65538
    loopback0: 207.254.21.153
  hostname: r27.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r28.cisco.com:
  data:
    asn: 65538
    loopback0: 55.229.193.11
  hostname: r28.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r29.cisco.com:
  data:
    asn: 65538
    loopback0: 67.110.241.176
  hostname: r29.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r3.cisco.com:
  data:
    asn: 65538
    loopback0: 205.62.20.108
  hostname: r3.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r30.cisco.com:
  data:
    asn: 65538
    loopback0: 195.205.213.60
  hostname: r30.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r31.cisco.com:
  data:
    asn: 65538
    loopback0: 180.209.138.127
  hostname: r31.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r32.cisco.com:
  data:
    asn: 65538
    loopback0: 104.239.115.96
  hostname: r32.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r33.cisco.com:
  data:
    asn: 65538
    loopback0: 22.75.65.252
  hostname: r33.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r34.cisco.com:
  data:
    asn: 65538
    loopback0: 211.243.112.12
  hostname: r34.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r35.cisco.com:
  data:
    asn: 65538
    loopback0: 78.116.218.138
  hostname: r35.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r36.cisco.com:
  data:
    asn: 65538
    loopback0: 70.230.171.61
  hostname: r36.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r37.cisco.com:
  data:
    asn: 65538
    loopback0: 66.176.134.94
  hostname: r37.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r38.cisco.com:
  data:
    asn: 65538
    loopback0: 44.196.6.218
  hostname: r38.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r39.cisco.com:
  data:
    asn: 65538
    loopback0: 217.254.123.173
  hostname: r39.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r4.cisco.com:
  data:
    asn: 65538
    loopback0: 64.234.188.215
  hostname: r4.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r40.cisco.com:
  data:
    asn: 65538
    loopback0: 69.58.157.30
  hostname: r40.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r41.cisco.com:
  data:
    asn: 65538
    loopback0: 134.157.43.163
  hostname: r41.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r42.cisco.com:
  data:
    asn: 65538
    loopback0: 4.28.188.188
  hostname: r42.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r43.cisco.com:
  data:
    asn: 65538
    loopback0: 220.121.143.226
  hostname: r43.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r44.cisco.com:
  data:
    asn: 65538
    loopback0: 167.137.169.70
  hostname: r44.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r45.cisco.com:
  data:
    asn: 65538
    loopback0: 211.201.94.166
  hostname: r45.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r46.cisco.com:
  data:
    asn: 65538
    loopback0: 76.23.44.228
  hostname: r46.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r47.cisco.com:
  data:
    asn: 65538
    loopback0: 42.31.70.219
  hostname: r47.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r48.cisco.com:
  data:
    asn: 65538
    loopback0: 159.194.93.113
  hostname: r48.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r49.cisco.com:
  data:
    asn: 65538
    loopback0: 54.26.208.35
  hostname: r49.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r5.cisco.com:
  data:
    asn: 65538
    loopback0: 27.159.175.86
  hostname: r5.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r50.cisco.com:
  data:
    asn: 65538
    loopback0: 31.218.80.98
  hostname: r50.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r51.cisco.com:
  data:
    asn: 65538
    loopback0: 18.100.118.140
  hostname: r51.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r52.cisco.com:
  data:
    asn: 65538
    loopback0: 80.195.164.208
  hostname: r52.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r53.cisco.com:
  data:
    asn: 65538
    loopback0: 11.211.173.12
  hostname: r53.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r54.cisco.com:
  data:
    asn: 65538
    loopback0: 181.156.244.222
  hostname: r54.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r55.cisco.com:
  data:
    asn: 65538
    loopback0: 97.98.232.33
  hostname: r55.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r56.cisco.com:
  data:
    asn: 65538
    loopback0: 65.97.61.222
  hostname: r56.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r57.cisco.com:
  data:
    asn: 65538
    loopback0: 175.77.217.182
  hostname: r57.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r58.cisco.com:
  data:
    asn: 65538
    loopback0: 26.229.70.31
  hostname: r58.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r59.cisco.com:
  data:
    asn: 65538
    loopback0: 204.187.248.9
  hostname: r59.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r6.cisco.com:
  data:
    asn: 65538
    loopback0: 73.69.60.114
  hostname: r6.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r60.cisco.com:
  data:
    asn: 65538
    loopback0: 223.115.18.188
  hostname: r60.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r61.cisco.com:
  data:
    asn: 65538
    loopback0: 101.196.113.208
  hostname: r61.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r62.cisco.com:
  data:
    asn: 65538
    loopback0: 67.81.40.200
  hostname: r62.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r63.cisco.com:
  data:
    asn: 65538
    loopback0: 2.244.35.207
  hostname: r63.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r64.cisco.com:
  data:
    asn: 65538
    loopback0: 47.85.47.12
  hostname: r64.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r65.cisco.com:
  data:
    asn: 65538
    loopback0: 107.76.118.247
  hostname: r65.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r66.cisco.com:
  data:
    asn: 65538
    loopback0: 148.185.85.77
  hostname: r66.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r67.cisco.com:
  data:
    asn: 65538
    loopback0: 197.47.2.5
  hostname: r67.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r68.cisco.com:
  data:
    asn: 65538
    loopback0: 49.69.57.41
  hostname: r68.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r69.cisco.com:
  data:
    asn: 65538
    loopback0: 216.13.71.155
  hostname: r69.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r7.cisco.com:
  data:
    asn: 65538
    loopback0: 79.252.197.253
  hostname: r7.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r70.cisco.com:
  data:
    asn: 65538
    loopback0: 36.114.226.133
  hostname: r70.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r71.cisco.com:
  data:
    asn: 65538
    loopback0: 215.112.227.51
  hostname: r71.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r72.cisco.com:
  data:
    asn: 65538
    loopback0: 171.36.239.153
  hostname: r72.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r73.cisco.com:
  data:
    asn: 65538
    loopback0: 118.159.75.196
  hostname: r73.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r74.cisco.com:
  data:
    asn: 65538
    loopback0: 61.134.194.78
  hostname: r74.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r75.cisco.com:
  data:
    asn: 65538
    loopback0: 164.111.168.77
  hostname: r75.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r76.cisco.com:
  data:
    asn: 65538
    loopback0: 188.170.212.87
  hostname: r76.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r77.cisco.com:
  data:
    asn: 65538
    loopback0: 144.49.176.144
  hostname: r77.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r78.cisco.com:
  data:
    asn: 65538
    loopback0: 176.151.197.144
  hostname: r78.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r79.cisco.com:
  data:
    asn: 65538
    loopback0: 41.207.137.9
  hostname: r79.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r8.cisco.com:
  data:
    asn: 65538
    loopback0: 207.59.95.16
  hostname: r8.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r80.cisco.com:
  data:
    asn: 65538
    loopback0: 210.130.224.71
  hostname: r80.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r81.cisco.com:
  data:
    asn: 65538
    loopback0: 60.235.116.233
  hostname: r81.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r82.cisco.com:
  data:
    asn: 65538
    loopback0: 121.62.82.103
  hostname: r82.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r83.cisco.com:
  data:
    asn: 65538
    loopback0: 190.82.249.36
  hostname: r83.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r84.cisco.com:
  data:
    asn: 65538
    loopback0: 52.127.71.7
  hostname: r84.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r85.cisco.com:
  data:
    asn: 65538
    loopback0: 94.46.163.79
  hostname: r85.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r86.cisco.com:
  data:
    asn: 65538
    loopback0: 176.219.232.33
  hostname: r86.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r87.cisco.com:
  data:
    asn: 65538
    loopback0: 222.96.206.167
  hostname: r87.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r88.cisco.com:
  data:
    asn: 65538
    loopback0: 212.155.216.118
  hostname: r88.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r89.cisco.com:
  data:
    asn: 65538
    loopback0: 202.211.125.136
  hostname: r89.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r9.cisco.com:
  data:
    asn: 65538
    loopback0: 69.74.221.123
  hostname: r9.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r90.cisco.com:
  data:
    asn: 65538
    loopback0: 160.119.237.242
  hostname: r90.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r91.cisco.com:
  data:
    asn: 65538
    loopback0: 33.231.42.33
  hostname: r91.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r92.cisco.com:
  data:
    asn: 65538
    loopback0: 70.63.158.156
  hostname: r92.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r93.cisco.com:
  data:
    asn: 65538
    loopback0: 134.231.168.91
  hostname: r93.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r94.cisco.com:
  data:
    asn: 65538
    loopback0: 121.48.198.96
  hostname: r94.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r95.cisco.com:
  data:
    asn: 65538
    loopback0: 221.233.211.187
  hostname: r95.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r96.cisco.com:
  data:
    asn: 65538
    loopback0: 172.196.234.148
  hostname: r96.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r97.cisco.com:
  data:
    asn: 65538
    loopback0: 15.211.186.164
  hostname: r97.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r98.cisco.com:
  data:
    asn: 65538
    loopback0: 166.81.40.126
  hostname: r98.cisco.com
  password: cisco123
  platform: ios
  username: cisco
r99.cisco.com:
  data:
    asn: 65538
    loopback0: 68.236.205.237
  hostname: r99.cisco.com
  password: cisco123
  platform: ios
  username: cisco
