r1.cisco.com:
  data:
    asn: 65538
    loopback0: 27.38.6.38
  hostname: r1.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r10.cisco.com:
  data:
    asn: 65538
    loopback0: 97.197.100.94
  hostname: r10.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r11.cisco.com:
  data:
    asn: 65538
    loopback0: 51.78.107.24
  hostname: r11.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r12.cisco.com:
  data:
    asn: 65538
    loopback0: 115.117.137.213
  hostname: r12.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r13.cisco.com:
  data:
    asn: 65538
    loopback0: 166.191.140.20
  hostname: r13.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r14.cisco.com:
  data:
    asn: 65538
    loopback0: 93.151.78.231
  hostname: r14.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r15.cisco.com:
  data:
    asn: 65538
    loopback0: 115.130.72.200
  hostname: r15.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r16.cisco.com:
  data:
    asn: 65538
    loopback0: 166.132.182.111
  hostname: r16.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r17.cisco.com:
  data:
    asn: 65538
    loopback0: 4.146.119.4
  hostname: r17.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r18.cisco.com:
  data:
    asn: 65538
    loopback0: 200.71.158.62
  hostname: r18.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r19.cisco.com:
  data:
    asn: 65538
    loopback0: 67.57.211.196
  hostname: r19.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r2.cisco.com:
  data:
    asn: 65538
    loopback0: 5.14.109.20
  hostname: r2.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r20.cisco.com:
  data:
    asn: 65538
    loopback0: 119.123.151.144
  hostname: r20.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r21.cisco.com:
  data:
    asn: 65538
    loopback0: 196.0.125.45
  hostname: r21.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r22.cisco.com:
  data:
    asn: 65538
    loopback0: 44.159.4.90
  hostname: r22.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r23.cisco.com:
  data:
    asn: 65538
    loopback0: 102.190.241.92
  hostname: r23.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r24.cisco.com:
  data:
    asn: 65538
    loopback0: 33.29.40.181
  hostname: r24.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r25.cisco.com:
  data:
    asn: 65538
    loopback0: 191.200.23.89
  hostname: r25.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r26.cisco.com:
  data:
    asn: 65538
    loopback0: 110.107.98.213
  hostname: r26.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r27.cisco.com:
  data:
    asn: 65538
    loopback0: 3.161.124.125
  hostname: r27.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r28.cisco.com:
  data:
    asn: 65538
    loopback0: 134.100.91.108
  hostname: r28.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r29.cisco.com:
  data:
    asn: 65538
    loopback0: 188.204.44.223
  hostname: r29.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r3.cisco.com:
  data:
    asn: 65538
    loopback0: 10.169.131.218
  hostname: r3.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r30.cisco.com:
  data:
    asn: 65538
    loopback0: 204.209.50.179
  hostname: r30.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r4.cisco.com:
  data:
    asn: 65538
    loopback0: 192.151.132.155
  hostname: r4.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r5.cisco.com:
  data:
    asn: 65538
    loopback0: 32.124.77.196
  hostname: r5.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r6.cisco.com:
  data:
    asn: 65538
    loopback0: 111.83.81.25
  hostname: r6.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r7.cisco.com:
  data:
    asn: 65538
    loopback0: 134.152.154.201
  hostname: r7.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r8.cisco.com:
  data:
    asn: 65538
    loopback0: 161.206.135.77
  hostname: r8.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
r9.cisco.com:
  data:
    asn: 65538
    loopback0: 146.175.27.66
  hostname: r9.cisco.com
  password: C1sc0!23
  platform: ios
  username: cisco
